import AblyProvider from './AblyProvider'
import Navbar from './Navbar'
import './global.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ably & Next.js fundamentals kit',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='p-12'>
          <AblyProvider>
            <Navbar />
            {children}
          </AblyProvider>
        </div>
      </body>
    </html>
  )
}
