import { Toaster } from 'react-hot-toast'
import Navbar from './Navbar'
import './global.css'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
const AblyProvider = dynamic(() => import('./AblyProvider'), {
  ssr: false
})

export const metadata: Metadata = {
  title: 'Ably & Next.js fundamentals kit',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='sm:p-12 p-4'>
          <AblyProvider>
            <Toaster />
            <Navbar />
            {children}
          </AblyProvider>
        </div>
      </body>
    </html>
  )
}
